export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INITI_INGREDIENTS='INITI_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILS = 'FETCH_INGREDIENTS_FAILS';

export const BURGER_PURCHASE_START = 'BURGER_PURCHASE_START';
export const BURGER_PURCHASE_INIT ='BURGER_PURCHASE_INIT';
export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAILS = 'BURGER_PURCHASE_FAILS';
export const BURGER_PURCHASE = 'BURGER_PURCHASE';

export const ORDER_FETCH_START = 'ORDER_FETCH_START';
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAILS = 'ORDER_FETCH_FAILS';
export const ORDER_FETCH = 'ORDER_FETCH'

export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAILS ='AUTH_FAILS';
export const CHECK_AUTH_TIMEOUT ='CHECK_AUTH_TIMEOUT';
export const AUTH ='AUTH';
export const CHECK_AUTH_DATA ='CHECK_AUTH_DATA'
export const AUTH_INITIATE_LOGOUT ='AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';